blacklist = ['aa', 'ae', 'ai', 'ao', 'au', 'ab', 'ac', 'af', 'ag', 'aj', 'ak', 'ap', 'aq', 'ar', 'av', 'az',
 'ba', 'bi', 'bo', 'bu',
 'ca', 'ce', 'ci', 'co', 'cu', 'cy',
 'da', 'de', 'di', 'du', 'dy',
 'ea', 'ee', 'eg', 'ej', 'ek', 'el', 'em', 'en', 'ep', 'eq', 'er', 'es', 'et', 'ev', 'ew', 'ex', 'ez', 'ei', 'eo', 'eu', 'ey',
 'fa', 'fe', 'fi', 'fo', 'fu', 'fy',
 'ga', 'ge', 'gi', 'gu', 'gy',
 'ha', 'ho', 'hu', 'hy',
 'ia', 'ie', 'ii', 'io', 'iu', 'iy',
 'ja', 'je', 'ji', 'jo', 'ju', 'jy',
 'ka', 'ke', 'ki', 'ko', 'ku', 'ky',
 'la', 'le', 'li', 'lo', 'lu', 'ly',
 'ma', 'mi', 'mo', 'mu',
 'na', 'ne', 'ni', 'nu', 'ny',
 'oa', 'oe', 'oi', 'oo', 'ou', 'oy',
 'pa', 'pe', 'pi', 'po', 'pu', 'py',
 'qa', 'qe', 'qi', 'qo', 'qu', 'qy',
 'ra', 're', 'ri', 'ro', 'ru', 'ry',
 'sa', 'se', 'si', 'su', 'sy',
 'ta', 'te', 'ti', 'tu', 'ty',
 'ua', 'ue', 'ui', 'uo', 'uu', 'uy',
 'va', 've', 'vi', 'vo', 'vu', 'vy',
 'wa', 'wi', 'wo', 'wu', 'wy',
 'xa', 'xe', 'xi', 'xo', 'xu', 'xy',
 'ya', 'yb', 'yc', 'yd', 'yf', 'yg', 'yh', 'yi', 'yj', 'yk', 'yl', 'ym', 'yn', 'yp', 'yq', 'yr', 'ys', 'yt', 'yu', 'yv', 'yw', 'yx', 'yy', 'yz',
 'za', 'ze', 'zi', 'zo', 'zu', 'zy']
